# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 24

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

blur = true

option_as_alt = "Both"
